//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBriscola.Strings.en {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBriscola.Strings.en.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a clubs.
        /// </summary>
        internal static string bastoni {
            get {
                return ResourceManager.GetString("bastoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The trump suit is.
        /// </summary>
        internal static string CartaBriscola {
            get {
                return ResourceManager.GetString("CartaBriscola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please insert the number of the card you want play.
        /// </summary>
        internal static string CartaDaGiocare {
            get {
                return ResourceManager.GetString("CartaDaGiocare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cards.
        /// </summary>
        internal static string carte {
            get {
                return ResourceManager.GetString("carte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In deck remains.
        /// </summary>
        internal static string CarteMazzo {
            get {
                return ResourceManager.GetString("CarteMazzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cups.
        /// </summary>
        internal static string coppe {
            get {
                return ResourceManager.GetString("coppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suits.
        /// </summary>
        internal static string denari {
            get {
                return ResourceManager.GetString("denari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a of.
        /// </summary>
        internal static string di {
            get {
                return ResourceManager.GetString("di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Played card.
        /// </summary>
        internal static string Giocata {
            get {
                return ResourceManager.GetString("Giocata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You lost for.
        /// </summary>
        internal static string HaiPersoPer {
            get {
                return ResourceManager.GetString("HaiPersoPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have won for.
        /// </summary>
        internal static string HaiVintoPer {
            get {
                return ResourceManager.GetString("HaiVintoPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value. Please insert a number between 1 and.
        /// </summary>
        internal static string InserisciNuovoNumero {
            get {
                return ResourceManager.GetString("InserisciNuovoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The game is over.
        /// </summary>
        internal static string PartitaFinita {
            get {
                return ResourceManager.GetString("PartitaFinita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The game is draw.
        /// </summary>
        internal static string PartitaPatta {
            get {
                return ResourceManager.GetString("PartitaPatta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Press return to exit.
        /// </summary>
        internal static string PremereInvio {
            get {
                return ResourceManager.GetString("PremereInvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ponts.
        /// </summary>
        internal static string punti {
            get {
                return ResourceManager.GetString("punti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Points of Cpu.
        /// </summary>
        internal static string PuntiCpu {
            get {
                return ResourceManager.GetString("PuntiCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Points.
        /// </summary>
        internal static string PuntiUtente {
            get {
                return ResourceManager.GetString("PuntiUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a spades.
        /// </summary>
        internal static string spade {
            get {
                return ResourceManager.GetString("spade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid value.
        /// </summary>
        internal static string ValoreNonValido {
            get {
                return ResourceManager.GetString("ValoreNonValido", resourceCulture);
            }
        }
    }
}
