//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBriscola.Strings.fr {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBriscola.Strings.fr.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a batons.
        /// </summary>
        internal static string bastoni {
            get {
                return ResourceManager.GetString("bastoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La couleur d&apos; atout.
        /// </summary>
        internal static string CartaBriscola {
            get {
                return ResourceManager.GetString("CartaBriscola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Veuillez insérer le numéro de la carte que vous voulez jouer.
        /// </summary>
        internal static string CartaDaGiocare {
            get {
                return ResourceManager.GetString("CartaDaGiocare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a cartes.
        /// </summary>
        internal static string carte {
            get {
                return ResourceManager.GetString("carte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dans le jeu ça reste.
        /// </summary>
        internal static string CarteMazzo {
            get {
                return ResourceManager.GetString("CarteMazzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a coupes.
        /// </summary>
        internal static string coppe {
            get {
                return ResourceManager.GetString("coppe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a deniers.
        /// </summary>
        internal static string denari {
            get {
                return ResourceManager.GetString("denari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a depuis.
        /// </summary>
        internal static string di {
            get {
                return ResourceManager.GetString("di", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carte jouée.
        /// </summary>
        internal static string Giocata {
            get {
                return ResourceManager.GetString("Giocata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur invalide. Veuillez insérer un nombre entre 1 et.
        /// </summary>
        internal static string InserisciNuovoNumero {
            get {
                return ResourceManager.GetString("InserisciNuovoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jeu terminé.
        /// </summary>
        internal static string PartitaFinita {
            get {
                return ResourceManager.GetString("PartitaFinita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Appuyez sur retour pour quitter.
        /// </summary>
        internal static string PremereInvio {
            get {
                return ResourceManager.GetString("PremereInvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Points de Cpu.
        /// </summary>
        internal static string PuntiCpu {
            get {
                return ResourceManager.GetString("PuntiCpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vos points.
        /// </summary>
        internal static string PuntiUtente {
            get {
                return ResourceManager.GetString("PuntiUtente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a epées.
        /// </summary>
        internal static string spade {
            get {
                return ResourceManager.GetString("spade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur invalide.
        /// </summary>
        internal static string ValoreNonValido {
            get {
                return ResourceManager.GetString("ValoreNonValido", resourceCulture);
            }
        }
    }
}
